cloud:
  aws:
    s3:
      bucket: baezzangee
    region:
      static: ap-northeast-2

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/baezzangee-local;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 1MB